# language: node_js
# node_js:
#   - 14
# cache:
#   directories:
#     - node_modules
# script:
#   - echo "No tests to run"

language: node_js
node_js:
  - "14"

cache:
  directories:
    - "node_modules"

install:
  - cd talentvault/backend
  - npm install

script:
  - npm test
