name: TalentVault CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}


    - name: Install backend dependencies
      run: npm ci
      working-directory: talentvault/backend

    #- name: Build
    #  run: npm run build
    #  working-directory: frontend
      
    - name: Run tests
      run: npm test
      working-directory: talentvault/backend
      env:
        CI: true
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        DATABASE_URI: ${{ secrets.DATABASE_URI }}
        PORT: ${{ secrets.PORT }}
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
    
    
    
  

      # - name: Install dependencies frontend
      #   working-directory: talentvault/frontend
      #   run: npm install

      # - name: Run tests frontend
      #   working-directory: talentvault/frontend
      #   run: |
      #     npm ci
      #     npm run build --if-present
